### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by chheiss** [dkarv/hacs-bwt-perla#1]
coming up during integration set up.

**Comment by dkarv** [comment]
Is there anything related in the logs? I just tried on my own instance and on a very freshly setup, both worked.
In the host field I entered the ip address of the bwt device, e.g _192.168.1.20_
and code is the Login-Code from bwt (6 characters in my case).

**Comment by chheiss** [comment]
Logger: custom_components.bwt_perla.config_flow
Source: custom_components/bwt_perla/config_flow.py:50
Integration: bwt_perla
First occurred: 20:35:29 (1 occurrences)
Last logged: 20:35:29

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/bwt_perla/config_flow.py", line 50, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bwt_perla/config_flow.py", line 32, in validate_input
    await api.get_current_data()
  File "/usr/local/lib/python3.11/site-packages/bwt_api/api.py", line 83, in get_current_data
    list(errors),
    ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bwt_api/api.py", line 68, in <lambda>
    lambda error: BwtError(int(error)), raw["ActiveErrorIDs"].split(",")
                           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

**Comment by dkarv** [comment]
I made a mistake parsing the errors if there are none. It should be fixed now, I pushed a new version and you can update within HACS.

**Comment by chheiss** [comment]
Works now! Thanks for that!!! Great integration.
