### ISSUE TITLE
Illogical water capacity display

### ISSUE THREAD

**Issue by Nitrox912** [dkarv/hacs-bwt-perla#11]
Device: BWT Perla
Version: 2.0209

Hello, I installed the integration a few days ago and noticed some discrepancies in the displayed water capacity in HA compared to the readings on the display of the system. What do the values in the integration mean?

<img width="363" alt="4" src="https://github.com/dkarv/hacs-bwt-perla/assets/127048498/02e283e9-f9c8-4487-887f-3e71956850ce">
<img width="686" alt="3" src="https://github.com/dkarv/hacs-bwt-perla/assets/127048498/8ac2028e-d7b2-4005-849e-7160f1837d8c">

**Comment by dkarv** [comment]
Interesting observation, I never checked it, I can reproduce it.
Regarding the other values, the BWT device shows treated water, while app and integration show blended water (more about the difference in #5).
But for the capacity it seems to be something different.
The [documentation](https://github.com/dkarv/hacs-bwt-perla/files/13864120/Dokumentation.API.pdf) states:

> Rest-Kapazität von Säule 1 (Vollenthärtetes Wasser)

so I just assumed the same formula applies here. To find the correct formula, we probably need to collect a few more datapoints:
| BWT    | Integration | Hardness In | Hardness Out |
| --------- | ---------------- | ------------------ | -------------------- |
| 325 | 8432 | 21 | 4 |
| 178 | 4626 | 21 | 4 |
| 14 | 406 | | |
| 257 | 7178 | | |

@Nitrox912 can you send your hardness in and out values, so I can add them to the table and play around with it?

**Comment by dkarv** [comment]
I might have found a pattern, still need to fully confirm it: The `API value` / `hardness_in` = `BWT display value` .

Now the interesting part is, what's the most useful value for users? Are the values shown on the BWT actual remaining capacities, meaning if they are zero it needs to refresh? If so they would be interesting and I could calculate them from the API values.

**Comment by Nitrox912** [comment]
In my system, the hardness in is set to 23 and the hardness out is set to 4.

This specification has the highest value to determine how much water each respective column can still soften before it needs to regenerate. I would prefer the value displayed by the BWT device in the integration.

However, I have no idea if the values even interest anyone. It was just about traceability for me.

**Comment by dkarv** [comment]
Thanks, it confirms my assumption. Based on past values from my device I can confirm the BWT shows the amount of water each column can still treat to 0°dH.
I feel, to make it consistent with the other values, I should calculate the amount of blended water a column can still produce. Then it matches the output values, difference in output = difference in sum of capacities.

I start the implementation. For future reference, the formula I came up with is `raw` / (`hardness_in` - `hardness_out`) and it matches past values.

**Comment by dkarv** [comment]
I released version v0.5.1 with the newly calculated values. Thanks for bringing it up.
