### ISSUE TITLE
bwt NEW ACCESS

### ISSUE THREAD

**Issue by LaCrapule** [dkarv/hacs-bwt-perla#13]
Hi !
Did you provide a support for BWT NEW ACCESS ?  
Thank's

**Comment by dkarv** [comment]
Hi,
probably your device does not offer a local api, which my integration is based on.
According to the official api documentation, only **BWT Perla und Rondomat Duo** are supported.

Maybe you could check the manual or contact the BWT support if there is a local api (planned).
