### ISSUE TITLE
Firmware availability

### ISSUE THREAD

**Issue by drsmarsden** [dkarv/hacs-bwt-perla#15]
Required firmware not available in UK 
Sept 2024

**Comment by dkarv** [comment]
Hey,
I am not involved with BWT in any way. I have no clue where and when the firmware is rolled out.
The firmware version required is still in beta, and only installed after requesting it. Some more information here: https://github.com/dkarv/hacs-bwt-perla/issues/3#issuecomment-1879816899

In case you tried this and the customer service told you it is not available in UK, could you please share their response for future reference? It might be helpful for other users.

**Comment by drsmarsden** [comment]
Hi,Sorry I cleared out all my old emails this morning I emailed ***@***.*** and was told they do not do firmware upgrades full stop.I then email the published DE contact, they checked my SN and said they can not issue firmware for the UKI then email the UK again to explain that it was available I was told not in the UKStuartSent from my iPadOn 5 Sep 2024, at 14:42, David ***@***.***> wrote:﻿
Hey,
I am not involved with BWT in any way. I have no clue where and when the firmware is rolled out.
The firmware version required is still in beta, and only installed after requesting it. Some more information here: #3 (comment)
In case you tried this and the customer service told you it is not available in UK, could you please share their response for future reference? It might be helpful for other users.
