### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by bernji** [dkarv/hacs-bwt-perla#2]
Hello,

Thanks for making this an HACS integration!
Can you please create releases / versioning so that it is easier to update your integration through HACS?

Thank you!

**Comment by dkarv** [comment]
Hello,

good idea.
I tried this during the last days, created various releases in different ways. But whatever I do, HACS always reports something `No assets found for release 'tags/v0.2.1'`.
Not sure what's wrong or what I'm missing, I will keep investigating...

**Comment by dkarv** [comment]
Finally with the help of the HACS maintainer in https://github.com/hacs/integration/issues/3445 I was able to fix this, so there is a working release v0.3.2 now.
