### ISSUE TITLE
Missing Error Entities

### ISSUE THREAD

**Issue by chrannen** [dkarv/hacs-bwt-perla#4]
Hi

Thanks for the great work for this hacs integration. I have sucessfully integrated BWT Perla in Home Assistant.

Next you find the documentation for the api (sorry, i only have the version in german).
> [Dokumentation API.pdf](https://github.com/dkarv/hacs-bwt-perla/files/13864120/Dokumentation.API.pdf)

In this document on page 7 is the data "ActiveErrorIDs" listet.
> ![image](https://github.com/dkarv/hacs-bwt-perla/assets/97344789/53f23d4c-a207-4960-9b89-0c1fdc5b6802)

And on page 8 is the state "ShowError" listet
> ![image](https://github.com/dkarv/hacs-bwt-perla/assets/97344789/dd18ee24-24e4-4785-9134-b4d30fc56342)

Is it possible to add these two entities into your HACS integration as well?

In your integration is an entity named "bwt perla state" available. I'm not sure if this entity shows one of the two mentioned errors...
> ![image](https://github.com/dkarv/hacs-bwt-perla/assets/97344789/e088a6e3-2913-480a-832e-74a538667ad7)

Thank you for checking my request.

Best regards,
Christian

**Comment by dkarv** [comment]
Hi

glad you like the integration. The errors are indeed the next thing on my list to add
`bwt perla state` = ShowError from the documentation. I think I should change its type and push text values like OK, WARNING and ERROR, makes more sense.

Regarding the list of errors: I'm still looking how to represent them in HA. Anybody knows another integration publishing a list of errors or in general a list of items? It would be a great starting point. Not sure if a entity can have a list value.
Currently the best I can do is a list of these error identifiers: https://github.com/dkarv/bwt_api/blob/main/src/bwt_api/error.py#L8

**Comment by chrannen** [comment]
> I think I should change its type and push text values like OK, WARNING and ERROR, makes more sense.

- Yes, i think that's a great development and makes the entity easier to understand.

> Regarding the list of errors: I'm still looking how to represent them in HA.

- This is actually not easy. Especially because several errors are combined as a string in one message.

Question: If you make changes in your HACS integration, will it show as an available update in HA-HACS? I'm not sure if this also works for custom integrations. Or do I have to reload (as a new custom download) your changes manually?

**Comment by dkarv** [comment]
I pushed a new version with the readable state (OK, WARNING and ERROR).
And list of errors and warnings. Both are comma-separated lists, or empty if there is no error.

> Question: If you make changes in your HACS integration, will it show as an available update in HA-HACS? I'm not sure if this also works for custom integrations. Or do I have to reload (as a new custom download) your changes manually?
I think it depends on a few factors, but for me they show up as update after a while. You can always force the update in HACS.

**Comment by dkarv** [comment]
For some reason the releases with versions don't work in my repository. I will open an issue in HACS to clarify.
I removed this version again, hopefully you get the update now showing the git tag 54a20aa.

If you don't get it automatically, you can open the integration in HACS and in the top right
![image](https://github.com/dkarv/hacs-bwt-perla/assets/3708591/5c3d971e-6c4d-4df4-9cba-24d7dc7f6939)
First pick Aktualisierungsinformationen , then Erneut herunterladen , and select master.

**Comment by chrannen** [comment]
Thank you so much! The attribute of the entity state is now "OK" 👌💪 The workaround (1st step “Aktualisierungsinformationen ”; 2nd step “Erneut herunterladen”; 3rd step “Master”) worked very well. Let's hope the auto-update issue can be resolved soon.

I noticed something else: In the entity "technician_service" there is the date of the "Inbetriebnahme" (28.02.2022) instead the date of the last service by a technician (03.04.2023). Could there be something wrong with this API link?

![image](https://github.com/dkarv/hacs-bwt-perla/assets/97344789/c03d38fc-cfca-4ec9-919d-e4709acfaaf2)

![image](https://github.com/dkarv/hacs-bwt-perla/assets/97344789/6db6d421-560b-4997-93a5-bf538b23b022)

If everything is OK from your point of view, it may of course be that the technician did not enter the date of his inspection in the BWT machine 🤷‍♂️🤦‍♂️🤷‍♀️

**Comment by dkarv** [comment]
Glad it worked now!
I checked the technician service date on my instance and directly in the API. It also reports the setup date (Inbetriebnahme) and not the last service date for me...
Guess they did not enter the date for both of us, or BWT has an issue, but there is nothing wrong in the integration.
