### ISSUE TITLE
Treated Water of the day/month/year

### ISSUE THREAD

**Issue by KrockX** [dkarv/hacs-bwt-perla#5]
Hi Dkarv,

first, thanks fo your Hard Work!
You said the API can´t hand out the Treated Water of the Day/Month /year but the API gives you exactly these. 
Can´t you instead of addy a Utility Meter in HA add these Sensors:
WaterTreatedCurrentDay_l
WaterTreatedCurrentMonth_l
WaterTreatedCurrentYear_l

And maby also the "CurrentFlowrate_l_h " ?

Thanks and Kind Regards 
KrockX

**Comment by Naboo2604** [comment]
@dkarv: i would also like to thank you for your good work!

It would be great if you can extend your integration with the values @KrockX mentioned.

The response of http://ip-address:8080/GetCurrentData (my Aqua Perla FW is 2.0209) including these values.

Inspired by the screenshot from @deepandsteven in the community thread [Link](https://community.home-assistant.io/t/bwt-best-water-tech-nology-support/270745/119?page=2), your integration and the custom card from https://github.com/AmoebeLabs/flex-horseshoe-card I created a visualization like this:

<img width="383" alt="image" src="https://github.com/dkarv/hacs-bwt-perla/assets/13333609/8870ea6e-4b2c-4794-98aa-a91203930ada">

...instead of showing flow/day it would be great to display the current flow of the BWT system...

Nice to have: there a two other values available

- CapacityColumn1_ml_dH
- CapacityColumn2_ml_dH

...so we could show the both columns and the fill level in realtime.... :-)

Files for the visualization available in my repo: [Link](https://github.com/Naboo2604/homeassistant)

Thanks and greets,
Naboo2604

**Comment by dkarv** [comment]
Happy you like the integration. The custom card is nice!

### daily / monthly statistics
Unfortunately **the treated water is not the consumed water**. This is mentioned towards the end in the documentation.
Basically the BWT takes incoming water and fully softens it to 0°dH (treated). Then the device mixes (or blends) it together with untreated water (let's say 21°dH) to get to the requested output hardness (e.g. 4°dH).

The daily/monthly and yearly data the API returns are treated water, while there is only one data point about the total blended = consumed water. In my eyes the treated water is not really interesting for users, it is just some internal thing we shouldn't care about. The water consumed in the house is the interesting one.

I tried to calculate the blended water from treated value. But the results don't fully match with the data from the BWT app:
![image](https://github.com/dkarv/hacs-bwt-perla/assets/3708591/57ca13bd-a29e-47f8-821a-20f1d0c60e50)

In the end I never implemented this cause some things are unclear: 
* Is it a rounding error cause we only get integer values for treated and hardness, while the bwt has more accurate ones?
* does the bwt calculate or measure the blended water?
* how accurate are the total output values even? Maybe somebody also reads their real water meter to HA and can compare

### CurrentFlowrate_l_h

By default, HA samples new values every 30 seconds. I played with reading the flowrate and was not happy with the results. It would just pick one flowrate at that very moment. Even when sampling more often, which is possible, the underlying issue stays the same.

Instead I'm still trying to calculate the flowrate from the total number. HA has [Derivative sensors](https://www.home-assistant.io/integrations/derivative/) for this, but they don't recalculate if the value stays the same (https://github.com/home-assistant/core/issues/83496) - so they don't work for this purpose.

My next attempt is to calculate the flowrate on my own from the difference in the total value.

### CapacityColumn1/2_ml_dH

Makes sense, I will add them the next days.

**Comment by KrockX** [comment]
Hi Darkv,
thanks for your feedback.

You are of course right about the current flow rate, that doesn't really make sense.

Yes, that's right, I took another look at the API documentation, which says that this is how it should be.

I would actually be surprised if the daily flow rate on the system display meant that (using my pictures as an example) 86 litres were taken at 0°dh.
I'll talk about this at work on Monday ;)

FYI the app calculates some of these numbers. 
And you can´t compare the real water meter with the one from the BWT Perla, the water which is used for regeneration is not counted by the device because it only passes the waterinlet and not the wateroutlet where the water meter is located.
 
![Curl](https://github.com/dkarv/hacs-bwt-perla/assets/129213130/dbfc19f3-7170-4cca-a1b4-bbf4b9259f9d)
![Perla](https://github.com/dkarv/hacs-bwt-perla/assets/129213130/10dbcb0f-fbc7-4730-bf02-22ee8a4c1ebf)

**Comment by Naboo2604** [comment]
Hi @dkarv, I read the API docu from BWT again and you are fully right - I overseen the small difference between "Ausgangswasser" and "Aufbereitetes Wasser" sorry for that. 

Indeed it make no sense for endusers to know how much 0°dH water the system produce....

Regarding CapacityColumn values - thank you in advance - if you have anything that I can test, please give me a ping :-)

greets, Naboo

**Comment by KrockX** [comment]
Hi @dkarv ,

I have now received a formula to convert the 0°DH daily/weekly/monthly values into the total water consumption (without the water that is consumed during regeneration).

Amount0°dH soft water (in liters) + amount0°dH soft water (in liters) × (set initial hardness / raw water hardness) for example:
83L+83L×(4/16)= 103.75 liters total water consumption

Can you implement that so that we get 3 New values?

It may takes some time till we get this from the API directly  as an value from the water Meter.

Thanks and Kind regards
Krockx

**Comment by dkarv** [comment]
Hi,

thanks for the interesting input, I understand your formula as:
```
blended = treated + treated * (hardness_out / hardness_in)
# which is the same as
blended = treated * (1 + hardness_out / hardness_in)
```
(assuming `set initial hardness` and `raw water hardness` are the values we get from the API).

The formula I calculated:
```
blended = treated / (1 - hardness_out / hardness_in)
```

I tried your formula (orange) and my formula (green) and compared it to the values from the app (red)
![image](https://github.com/dkarv/hacs-bwt-perla/assets/3708591/838b6c9b-eed2-4176-aad5-2c97e6d662cf)

So something must be wrong... From a first look, my formula seems closer to the values from the app.

How I came up with my formula for reference:
```# I assume the outgoing hardness is the weighted sum of water mix
# treated = 0dH = not adding anything to outgoing hardness
# untreated = hardness_in dH = adding hardness
# Everything divided by the total amount of outgoing water

hardness_out = (treated * 0 + untreated * hardness_in) / (treated + untreated)     | untreated = blended - treated
hardness_out = ((blended - treated) * hardness_in) / (treated + blended - treated)
hardness_out = ((blended - treated) * hardness_in) / blended                       | / hardness_in
hardness_out / hardness_in = (blended - treated) / blended
hardness_out / hardness_in = blended / blended - treated / blended
hardness_out / hardness_in = 1 - treated / blended                                 | * blended
blended * (hardness_out / hardness_in) = blended - treated                         | - blended
blended * (hardness_out / hardness_in) - blended = - treated
(hardness_out / hardness_in - 1) * blended = - treated                             | / (hardness_out / hardness_in - 1)
blended = - treated / (hardness_out / hardness_in - 1)
blended = treated / (1 - hardness_out / hardness_in)

```

**Comment by KrockX** [comment]
Hi@dkarv ,

thanks for your reply.

I forwarded this to the Research Team and will give you Feedback as soon as i hear from them.

Kind Regards
Krockx

**Comment by dkarv** [comment]
I now had a look at the API the BWT app is using: it returns exact data while only showing rounded values to the user.
My formula matches exactly the raw values from the app API, so I'm assuming my formula is correct and I can implement it. :tada: 
![image](https://github.com/dkarv/hacs-bwt-perla/assets/3708591/8c14a068-a4ed-47b1-9516-324140824965)

**Comment by dkarv** [comment]
I just published a new beta release that adds all the requested entities: https://github.com/dkarv/hacs-bwt-perla/releases/tag/v0.4.0-beta

Please note that capacity and the daily, monthly and yearly consumption is blended water, calculated from the treated water.

Regarding the flow rate, I am actually not sure what the BWT reports, so I forward it as is. Regarding the flow rate, initially it is fetched every 30 seconds to not consume too many system resources. But once water is flowing, I refresh every second to get a nice graph:
![image](https://github.com/dkarv/hacs-bwt-perla/assets/3708591/01b869e7-ffba-4072-b7b8-36df5696491d)

As a result we could totally miss short water flows, like the red one in the image.

I will test the changes a few days before releasing them, but you are welcome to try the beta.

**Comment by KrockX** [comment]
Hi @dkarv,
thanks for the Update.
looks good so far and seems to match with the updated Version of the Formular which is used in the app and on the Maschines.
See attached picture. (only in german sorry for that if needed i send un an updated version in english)
![image](https://github.com/dkarv/hacs-bwt-perla/assets/129213130/af9958a0-4160-41c6-b319-dacd3a99672c)
![image](https://github.com/dkarv/hacs-bwt-perla/assets/129213130/e97d0d07-84e6-4581-85c6-ba57d7c1116a)
![image](https://github.com/dkarv/hacs-bwt-perla/assets/129213130/1a650b1d-d9fa-49a9-ae95-e19bef5c4afa)
